### PR TITLE
[FEATURE] make first version of frontend template

### PR DESCRIPTION
**Pull request by kkshyu**
feel free to give suggestions

for css module part, we should do ourselves
the convention of class naming is: {filename}__{classname}
ex. for the table in homepage, we will use `homepage__talbe`

if there is any problem, feel free to comment

### CODE REVIEW

**Comment by kkshyu** [comment]
@jacklam718 i just merged yours into mine followed by antd 
please check for it ~

**Comment by jacklam718** [comment]
@kkshyu I think we should keep keep consistent for naming convention, I saw some css class names using double underscore and some are using train-case.

**Comment by kkshyu** [comment]
Double underscore means the hierarchical structure. Train case use in the same level. For example, if u have a component called LoginModal, we will use .login-modal for its class name. And its title, we will use .login-modal__title as the class name.

**Comment by kkshyu** [comment]
Why we need double underscores is to avoid the conflict of global scope. CSS module follows the rule, too. Please check this https://medium.freecodecamp.org/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849
Of course, double dashes is ok, too

**Pull request merged**
